/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import beans.Usuario;
import datos.ConexionBD;
import datos.UsuarioDAO;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author roberto
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Usuario u;
    UsuarioDAO udao;
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon icono=new ImageIcon(ClassLoader.getSystemResource("imagenes/logo.png"));
        this.setIconImage(icono.getImage());
        u=new Usuario();
        udao=new UsuarioDAO();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconLogin = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblPwd = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPwd = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACCESO A AGROERP");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        getContentPane().add(iconLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        lblUsuario.setText("Usuario:");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        lblPwd.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblPwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/password.png"))); // NOI18N
        lblPwd.setText("Password:");
        getContentPane().add(lblPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        txtUser.setBackground(new java.awt.Color(0, 0, 153));
        txtUser.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
        });
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 130, -1));

        txtPwd.setBackground(new java.awt.Color(0, 0, 153));
        txtPwd.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtPwd.setForeground(new java.awt.Color(255, 255, 255));
        txtPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPwdKeyPressed(evt);
            }
        });
        getContentPane().add(txtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 130, -1));

        btnEntrar.setBackground(new java.awt.Color(0, 102, 153));
        btnEntrar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Iniciar Sesión");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        lblMsg.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 290, 240, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        if(txtUser.getText().isEmpty()||txtPwd.getText().isEmpty())
            lblMsg.setText("!!Se deben informar los campos!!");
        else{
            u.setNombre(txtUser.getText());
            u.setClave(txtPwd.getText());
            if(udao.validar(u)){
                Principal p=new Principal(u);
                p.pack();
                p.setVisible(true);
                this.dispose();
            }
            else{
                lblMsg.setText("!!Datos de sesion incorrectos!!");
            }
        }
            
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        lblMsg.setText("");
    }//GEN-LAST:event_txtUserKeyPressed

    private void txtPwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPwdKeyPressed
       lblMsg.setText("");
    }//GEN-LAST:event_txtPwdKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ConexionBD.cerrar();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconLogin;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
